micronaut:
  application:
    name: micronaut-java
    version: v1
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
    versioning:
      header:
        enabled: true

  server:
    port: 9092

datasources:
  default:
    url: jdbc:h2:mem:localdb;DB_CLOSE_DELAY=-1
    password: test
    driverClassName: org.h2.Driver
    dialect: H2
    schema-generate: CREATE_DROP
    username: sa

netty:
  default:
    allocator:
      max-order: 3

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
    entity-scan:
      packages: com.rjtmahinay.entity
      enabled: true

endpoints:
  loggers:
    enabled: true
  beans:
    enabled: true
  routes:
    enabled: true

example:
  value: test

