name: Docker Image CI

on:
  push:
    branches: [ "master", "branches" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 17
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: artifact
          path: /build/
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          file: /build/docker/native-man/DockerfileNative
          tags: rjtmahinay/micronaut-java:latest
