name: Docker Image CI

on:
  push:
    branches:
      - "master"
      - "feature-docker"
    paths:
      - ".github/workflows/docker-image.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build Micronaut
      - uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build dockerfileNative
      - name: Upload artifact
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: artifact
          path: build/docker/native-main/DockerfileNative
  deployment:
    needs: build
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: artifact
          path: temp
      - name: Build the Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          file: DockerfileNative
          tags: rjtmahinay/micronaut-java:latest
