name: micronaut-java CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
    paths:
      - ".github/workflows/workflow.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build and Test Micronaut
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build